name: checklist_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_staggered_grid_view: ^0.6.2
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  go_router: ^4.3.0
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  overlay_support: ^2.0.1
  provider: ^6.0.3
  uuid: ^3.0.6

dev_dependencies:
  device_preview: ^1.1.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
